Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -23,7 +23,7 @@ jobs:
         run: |
           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git config --local user.name "github-actions[bot]"
-          git commit -m "[dependabot skip] Update environment" -a && echo "commit_status=success" >> $GITHUB_OUTPUT || echo "commit_status=failure" >> $GITHUB_OUTPUT
+          git commit -m "[dependabot skip] Update environment" -a && echo "commit_status=success" >> $GITHUB_ENV || echo "commit_status=failure" >> $GITHUB_ENV
       - name: UpdateDependabotPR push
         uses: ad-m/github-push-action@master
         with:
@@ -31,7 +31,8 @@ jobs:
           github_token: ${{ secrets.DEPENDABOT_WORKFLOW_TOKEN }}
       - name: Validate last commit
         shell: bash -l {0}
-        run: status=${{ steps.vars.outputs.commit_status }}; echo "$status"; if [[ "$status" == "failure" ]]; then exit 1; fi;
+        run: status=${{ env.commit_status }}; echo "$status"; if [[ "$status" == "failure" ]]; then exit 1; fi;
+        
 
   linux_x64_test_environment:
     needs: [dependabot_check]
